const playerNames = [
  "Josef Rines",
  "Ashley Sabado",
  "Howard Stevenson",
  "Cletus Heaton",
  "Jeffrey Mccalley",
  "Michel Roche",
  "Irvin Penick",
  "Stacy Pawlak",
  "Jesse Alles",
  "Shawn Speer",
  "Faustino Straker",
  "Dorsey Linda",
  "Gerald Cheatwood",
  "Brendan Danos",
  "Ricardo Ceja",
  "Garret Barreras",
  "Antone Stipe",
  "Jaime Roles",
  "Major Hollenbach",
  "Wilbert Levingston",
  "Marcelino Spurrier",
  "Raphael Purdom",
  "Ollie Pardon",
  "Hal Mcghie",
  "Sherman Johansson",
  "Evan Haberle",
  "Brice Masson",
  "Stan Barlow",
  "Kyle Yeh",
  "Fidel Milliner",
  "Lazaro Digman",
  "Ricky Lango",
  "Gregorio Lundstrom",
  "Lyndon Rotunno",
  "Enrique Grasser",
  "Wilton Kidd",
  "Mitchell Lavallee",
  "Giuseppe Doolittle",
  "Leopoldo Wanke",
  "Toby Goulette",
  "Rick Locklear",
  "Hong Klutts",
  "Delmer Heineman",
  "Jewel Hicklin",
  "Edgar Riordan",
  "Kieth Crigger",
  "Taylor Bushard",
  "Eldon Cifuentes",
  "Monroe Klump",
  "Gerardo Gosse"
];

const teams = [
  { location: "Phoenix", team: "Diamondbacks", state: "AZ" },
  { location: "Atlanta", team: "Braves", state: "GA" },
  { location: "Baltimore", team: "Orioles", state: "MD" },
  { location: "Boston", team: "Red Sox", state: "MA" },
  { location: "Chicago", team: "White Sox", state: "IL" },
  { location: "Chicago", team: "Cubs", state: "IL" },
  { location: "Cincinnati", team: "Reds", state: "OH" },
  { location: "Cleveland", team: "Indians", state: "OH" },
  { location: "Denver", team: "Rockies", state: "CO" },
  { location: "Detroit", team: "Tigers", state: "MI" },
  { location: "Houston", team: "Astros", state: "TX" },
  { location: "Kansas City", team: "Royals", state: "KS" },
  { location: "Los Angeles", team: "Angels", state: "CA" },
  { location: "Los Angeles", team: "Dodgers", state: "CA" },
  { location: "Miami", team: "Marlins", state: "FL" },
  { location: "Milwaukee", team: "Brewers", state: "WI" },
  { location: "Minnesota", team: "Twins", state: "MN" },
  { location: "New York City", team: "Yankees", state: "NY" },
  { location: "New York City", team: "Mets", state: "NY" },
  { location: "Oakland", team: "Athletics", state: "CA" },
  { location: "Philadelphia", team: "Phillies", state: "PA" },
  { location: "Pittsburgh", team: "Pirates", state: "PA" },
  { location: "San Diego", team: "Padres", state: "CA" },
  { location: "San Francisco", team: "Giants", state: "CA" },
  { location: "Seattle", team: "Mariners", state: "WA" },
  { location: "St. Louis", team: "Cardinals", state: "MO" },
  { location: "Tampa", team: "Rays", state: "FL" },
  { location: "Dallas", team: "Rangers", state: "TX" },
  { location: "Toronto", team: "Blue Jays", state: "ON" },
  { location: "Washington", team: "Nationals", state: "DC" }
];

const teamNames = [
  "Diamondbacks",
  "Braves",
  "Orioles",
  "Red Sox",
  "White Sox",
  "Cubs",
  "Reds",
  "Indians",
  "Rockies",
  "Tigers",
  "Astros",
  "Royals",
  "Angels",
  "Dodgers",
  "Marlins",
  "Brewers",
  "Twins",
  "Yankees",
  "Mets",
  "Athletics",
  "Phillies",
  "Pirates",
  "Padres",
  "Giants",
  "Mariners",
  "Cardinals",
  "Rays",
  "Rangers",
  "Blue Jays",
  "Nationals"
];

const states = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY"
];

const standings = [
  { team: "Astros", wins: 107, losses: 55 },
  { team: "Dodgers", wins: 106, losses: 56 },
  { team: "Yankees", wins: 103, losses: 59 },
  { team: "Twins", wins: 101, losses: 61 },
  { team: "Athletics", wins: 97, losses: 65 },
  { team: "Braves", wins: 97, losses: 65 },
  { team: "Rays", wins: 96, losses: 66 },
  { team: "Indians", wins: 93, losses: 69 },
  { team: "Nationals", wins: 93, losses: 69 },
  { team: "Cardinals", wins: 91, losses: 71 },
  { team: "Brewers", wins: 89, losses: 73 },
  { team: "Mets", wins: 86, losses: 76 },
  { team: "Diamondbacks", wins: 85, losses: 77 },
  { team: "Red Sox", wins: 84, losses: 78 },
  { team: "Cubs", wins: 84, losses: 78 },
  { team: "Phillies", wins: 81, losses: 81 },
  { team: "Rangers", wins: 78, losses: 84 },
  { team: "Giants", wins: 77, losses: 85 },
  { team: "Reds", wins: 75, losses: 87 },
  { team: "White Sox", wins: 72, losses: 89 },
  { team: "Angels", wins: 72, losses: 90 },
  { team: "Rockies", wins: 71, losses: 91 },
  { team: "Padres", wins: 70, losses: 92 },
  { team: "Pirates", wins: 69, losses: 93 },
  { team: "Mariners", wins: 68, losses: 94 },
  { team: "Blue Jays", wins: 67, losses: 95 },
  { team: "Royals", wins: 59, losses: 103 },
  { team: "Marlins", wins: 57, losses: 105 },
  { team: "Orioles", wins: 54, losses: 108 },
  { team: "Tigers", wins: 47, losses: 114 }
];

module.exports = {
  playerNames,
  teams,
  teamNames,
  states,
  standings
};
